const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const source = fs.readFileSync(path.join(root, 'pages', 'clients.vue'), 'utf8')

assert.match(source, /middleware:\s*['"]auth['"]/)
assert.match(source, /history\/getAllArchivedOrders/)
assert.match(source, /buildArchivedClientRows/)
assert.match(source, /buildArchivedClientsMetrics/)
assert.match(source, /buildArchivedClientsCsv/)
assert.match(source, /Nombre de client/)
assert.match(source, /Commandes avec numero/)
assert.match(source, /Clients inactifs/)
assert.match(source, /Taux de retour/)
assert.match(source, /Telecharger CSV/)
assert.match(source, /downloadClientsCsv/)
assert.match(source, /mdi-account-multiple-outline/)
assert.match(source, /mdi-phone-check-outline/)
assert.match(source, /mdi-account-clock-outline/)
assert.match(source, /mdi-repeat/)
assert.match(source, /metric\.icon/)
assert.match(source, /value:\s*['"]phone['"]/)
assert.match(source, /value:\s*['"]topNames['"]/)
assert.match(source, /value:\s*['"]orderCount['"]/)
assert.match(source, /value:\s*['"]totalSpent['"]/)
assert.match(source, /value:\s*['"]averageSpent['"]/)
assert.match(source, /value:\s*['"]firstOrderAt['"]/)
assert.match(source, /value:\s*['"]lastVisitDays['"]/)
assert.match(source, /formatCurrency\(item\.totalSpent\)/)
assert.match(source, /formatCurrency\(item\.averageSpent\)/)
assert.match(source, /item\.lastVisitLabel/)

console.log('clients page tests passed')
