const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const pageSource = fs.readFileSync(path.join(root, 'pages', 'borne.vue'), 'utf8')
const layoutSource = fs.readFileSync(path.join(root, 'layouts', 'default.vue'), 'utf8')

assert.match(pageSource, /middleware:\s*['"]auth['"]/)
assert.match(pageSource, /class="kiosk-page/)
assert.match(pageSource, /products\/getProducts/)
assert.match(pageSource, /this\.\$store\.get\('products\/dataProduct'\)/)
assert.doesNotMatch(pageSource, /products\/dataProducts/)
assert.doesNotMatch(pageSource, /categories\/getAllCategories/)
assert.match(pageSource, /shop\/getCurrentShopInfo/)
assert.doesNotMatch(pageSource, /shop\/getShopInfo['"]/)
assert.match(pageSource, /servicePointId/)
assert.match(pageSource, /this\.\$store\.get\('users\/user'\)/)
assert.doesNotMatch(pageSource, /localStorage\.getItem\('service_point_id'\)/)
assert.match(pageSource, /Votre commande/)
assert.match(pageSource, /Sur place/)
assert.match(pageSource, /A emporter/)
assert.match(pageSource, /mdi-silverware-fork-knife/)
assert.match(pageSource, /mdi-shopping/)
assert.match(pageSource, /kioskStep/)
assert.match(pageSource, /startNewOrder/)
assert.match(pageSource, /chooseSaleMode/)
assert.match(pageSource, /openCustomerNameStep/)
assert.match(pageSource, /openCustomerPhoneStep/)
assert.match(pageSource, /appendKeyboardValue/)
assert.match(pageSource, /keyboardTarget/)
assert.match(pageSource, /nameKeyboardRows/)
assert.match(pageSource, /A', 'Z', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P/)
assert.match(pageSource, /mdi-close-circle/)
assert.match(pageSource, /mdi-arrow-up-bold/)
assert.match(pageSource, /mdi-backspace-outline/)
assert.match(pageSource, /mdi-keyboard-space/)
assert.match(pageSource, /kiosk-keyboard-input-wrap/)
assert.match(pageSource, /kiosk-shift-key/)
assert.match(pageSource, /kiosk-space-key/)
assert.match(pageSource, /kiosk-backspace-key/)
assert.match(pageSource, /toggleKeyboardCase/)
assert.match(pageSource, /type:\s*'shift'/)
assert.match(pageSource, /type:\s*'backspace'/)
const nameControlRowStart = pageSource.indexOf('kiosk-keyboard-control-row')
const nameDialogActionsStart = pageSource.indexOf('</v-card-text>', nameControlRowStart)
const nameControlRowSource = pageSource.slice(
  nameControlRowStart,
  nameDialogActionsStart
)
assert.doesNotMatch(nameControlRowSource, /kiosk-backspace-key/)
assert.doesNotMatch(nameControlRowSource, /Effacer/)
assert.doesNotMatch(pageSource, /nameKeyboardKeys:\s*'ABCDEFGHIJKLMNOPQRSTUVWXYZ'/)
assert.doesNotMatch(pageSource, />\s*Vider\s*</)
assert.match(pageSource, /kiosk-welcome/)
assert.match(pageSource, /kiosk-welcome-mosaic/)
assert.match(pageSource, /welcomeAnimationMode/)
assert.match(pageSource, /startWelcomeAnimationRotation/)
assert.match(pageSource, /stopWelcomeAnimationRotation/)
assert.match(pageSource, /setInterval[\s\S]*10000/)
assert.match(pageSource, /clearInterval\(this\.welcomeAnimationTimer\)/)
assert.match(pageSource, /kiosk-welcome-mosaic--diagonal/)
assert.match(pageSource, /kiosk-welcome-mosaic--horizontal/)
assert.match(pageSource, /kioskMosaicHorizontalTop/)
assert.match(pageSource, /kioskMosaicHorizontalBottom/)
assert.match(pageSource, /welcomeShuffleSeed/)
assert.match(pageSource, /welcomeShuffledProductImages/)
assert.match(pageSource, /welcomeHorizontalRows/)
assert.match(pageSource, /welcomeDiagonalColumns/)
assert.match(pageSource, /welcomeRepeatedProductImages/)
assert.match(pageSource, /minimumLength = Math\.max\(48, images\.length\)/)
assert.match(pageSource, /v-for="row in welcomeHorizontalRows"/)
assert.match(pageSource, /v-for="column in welcomeDiagonalColumns"/)
assert.match(pageSource, /kiosk-welcome-mosaic-row--top/)
assert.match(pageSource, /kiosk-welcome-mosaic-row--bottom/)
assert.match(pageSource, /aspect-ratio="1"/)
const welcomeMosaicStart = pageSource.indexOf('kiosk-welcome-mosaic')
const welcomeContentStart = pageSource.indexOf('kiosk-welcome-content')
const welcomeMosaicSource = pageSource.slice(
  welcomeMosaicStart,
  welcomeContentStart
)
assert.match(welcomeMosaicSource, /aspect-ratio="1"/)
assert.doesNotMatch(welcomeMosaicSource, /\scontain(?:\s|\/|>)/)
assert.match(pageSource, /--kiosk-welcome-tile-size: min\(340px, 27vw\)/)
assert.doesNotMatch(pageSource, /--kiosk-welcome-diagonal-tile-size/)
assert.match(pageSource, /inset: 10% -24% -34% 14%/)
assert.match(pageSource, /kiosk-welcome-mosaic-column--2/)
assert.match(pageSource, /kiosk-welcome-mosaic-column--3/)
assert.match(pageSource, /gap: 52px/)
assert.match(pageSource, /width: var\(--kiosk-welcome-tile-size\)/)
assert.match(pageSource, /const modes = \['mixedHorizontal', 'diagonal', 'horizontal'\]/)
assert.match(pageSource, /this\.welcomeShuffleSeed = Date\.now\(\)/)
assert.match(pageSource, /welcomeProductImages/)
assert.match(pageSource, /productImageSrc\(image\)/)
assert.match(pageSource, /kiosk-welcome-content/)
assert.match(pageSource, /border-radius: 12px/)
assert.match(pageSource, /\.kiosk-welcome-mosaic-tile ::v-deep \.v-image[\s\S]*overflow: hidden/)
assert.match(pageSource, /\.kiosk-welcome-mosaic-tile ::v-deep \.v-image__image[\s\S]*border-radius: 12px/)
assert.doesNotMatch(pageSource, /background:\s*#111827/)
assert.match(pageSource, /\.kiosk-welcome[\s\S]*background:\s*#ffffff/)
assert.doesNotMatch(pageSource, /kiosk-welcome-overlay/)
assert.doesNotMatch(pageSource, /radial-gradient\(circle at center/)
assert.doesNotMatch(pageSource, /filter:\s*blur/)
assert.match(pageSource, /kiosk-mode-dialog/)
assert.match(pageSource, /kiosk-name-dialog/)
assert.match(pageSource, /kiosk-phone-dialog/)
assert.match(pageSource, /kiosk-side-categories/)
assert.match(pageSource, /categoryTiles/)
assert.match(pageSource, /kiosk-category-image/)
assert.match(pageSource, /categoryImageSrc\(category\.image\)/)
assert.match(pageSource, /\/api\/v1\/imgcategories\//)
assert.match(pageSource, /category\.name === activeCategory/)
assert.match(pageSource, /activeCategory = category\.name/)
assert.match(pageSource, /kiosk-bottom-cart/)
assert.match(pageSource, /kiosk-cart-item-card/)
assert.match(pageSource, /kiosk-cart-item-image/)
assert.match(pageSource, /productImageSrc\(item\.image\)/)
assert.match(pageSource, /kiosk-cart-item-main/)
assert.match(pageSource, /kiosk-cart-item-meta/)
assert.match(pageSource, /customizationList/)
assert.match(pageSource, /mdi-delete-outline/)
assert.match(pageSource, /mdi-cart-check/)
assert.match(pageSource, /Commander/)
assert.match(pageSource, /Annuler/)
assert.doesNotMatch(
  pageSource,
  /v-model\.trim="customer"[\s\S]*label="Votre nom"[\s\S]*v-model\.trim="phone"/
)
assert.match(layoutSource, /isKioskRoute/)
assert.match(layoutSource, /!isKioskPage/)
assert.match(pageSource, /ProductCustomizationWizard/)
assert.match(pageSource, /customizationDialog/)
assert.match(pageSource, /checkoutDisabled/)
assert.match(pageSource, /checkoutErrorMessage/)
assert.match(pageSource, /mdi-minus/)
assert.match(pageSource, /mdi-plus/)
assert.match(pageSource, /buildKioskCheckoutPayload/)
assert.match(pageSource, /getKioskOrderReference/)
assert.match(pageSource, /submitPayAtCounter/)
assert.match(pageSource, /submitStripe/)
const showCounterStart = pageSource.indexOf('    showCounterPayment() {')
const showStripeStart = pageSource.indexOf('    showStripePayment() {')
const hasPreparedStart = pageSource.indexOf('    hasPreparedStripeAttempt() {')
const showCounterSource = pageSource.slice(showCounterStart, showStripeStart)
const showStripeSource = pageSource.slice(showStripeStart, hasPreparedStart)
assert.match(showCounterSource, /return true/)
assert.match(showStripeSource, /return false/)
assert.match(pageSource, /cart\/checkoutOrder/)
assert.doesNotMatch(pageSource, /cart\/checkoutCounterPayBefore/)
assert.match(pageSource, /cart\/checkoutOrder/)
assert.match(pageSource, /buildPayload\('À encaisser', false\)/)
assert.match(pageSource, /source:\s*'borne'/)
assert.match(pageSource, /mountStripePayment/)
assert.match(pageSource, /confirmStripePayment/)
assert.match(pageSource, /stripePaymentElement/)
assert.match(pageSource, /Nouvelle commande/)
assert.match(pageSource, /numero de commande/)
assert.match(pageSource, /buildOrderTicketPayload/)
assert.match(pageSource, /sendOrderTicket/)
assert.match(pageSource, /printKioskReceipt/)
assert.match(pageSource, /Ticket imprime/)
assert.match(pageSource, /Ticket indisponible/)
assert.match(pageSource, /orders\/getAllOrder/)
assert.match(pageSource, /orders\/getDetailOrder/)
assert.match(pageSource, /stripePaymentReference/)
assert.match(pageSource, /kioskStep === 'payment' && !stripePaymentReady/)
assert.match(pageSource, /:disabled="checkoutDisabled \|\| Boolean\(checkoutLoading\)"/)

const confirmStripePaymentStart = pageSource.indexOf(
  '    async confirmStripePayment() {'
)
const finishCheckoutStart = pageSource.indexOf('    async finishCheckout(', confirmStripePaymentStart)
const confirmStripePaymentSource = pageSource.slice(
  confirmStripePaymentStart,
  finishCheckoutStart
)
assert.match(confirmStripePaymentSource, /catch \(error\)[\s\S]*checkoutErrorMessage/)

const resetKioskStart = pageSource.indexOf('    resetKiosk() {', finishCheckoutStart)
const finishCheckoutSource = pageSource.slice(finishCheckoutStart, resetKioskStart)
assert.match(
  finishCheckoutSource,
  /await this\.printKioskReceipt\(reference\.orderId, paymentMethod\)/
)
assert.match(finishCheckoutSource, /Ticket imprime/)
assert.match(finishCheckoutSource, /Ticket indisponible/)

console.log('kiosk page tests passed')
