const assert = require('assert')
const fs = require('fs')
const path = require('path')

const source = fs.readFileSync(
  path.join(__dirname, '../pages/reports.vue'),
  'utf8'
)

assert.ok(!source.includes('v-tabs'))
assert.ok(!source.includes('<v-tab'))
assert.ok(!source.includes('<v-tabs-items'))
assert.ok(!source.includes('Commandes</v-tab>'))
assert.ok(source.includes('Clôture Z'))
assert.ok(source.includes('Historique Z'))
assert.ok(source.indexOf('Clôture Z') < source.indexOf('Historique Z'))
assert.ok(source.includes('class="reports-page full-width pa-5"'))
assert.ok(source.includes('reports-hero'))
assert.ok(source.includes('reports-summary'))
assert.ok(source.includes('reports-kpi'))
assert.ok(source.includes('reports-panel'))
assert.ok(source.includes('reports-z-current'))
assert.ok(source.includes('v-skeleton-loader'))
assert.ok(source.includes('Aucun Ticket Z clôturé'))
assert.ok(source.includes('Aucun paiement sur cette période'))
assert.ok(source.includes('Aucune TVA sur cette période'))
assert.ok(source.includes('currentClosure'))
assert.ok(source.includes('closureHistory'))
assert.ok(source.includes('summaryCards'))
assert.ok(source.includes('paymentRows'))
assert.ok(source.includes('vatRows'))
assert.ok(source.includes('closeClosureDialog'))
assert.ok(source.includes('cashClosures/getCurrent'))
assert.ok(source.includes('cashClosures/getHistory'))
assert.ok(source.includes('cashClosures/closeCurrent'))
assert.ok(source.includes('cashClosures/getDetail'))
assert.ok(source.includes('cashClosures/detail'))
assert.ok(source.includes('selectedClosureDetail'))
assert.ok(source.includes('Clôturer la caisse'))
assert.ok(source.includes('Ticket Z'))
assert.ok(source.includes('payments_summary'))
assert.ok(source.includes('vat_summary'))
assert.ok(source.includes(':disabled="closingClosure || !canCloseClosure"'))
assert.ok(source.includes('Date de cloture'))
assert.ok(source.includes('Operateur'))
assert.ok(source.includes('closed_by_name'))
assert.ok(source.includes('selectedClosureDetail.payments_summary'))
assert.ok(source.includes('selectedClosureDetail.vat_summary'))
assert.ok(source.includes('mdi-printer'))
assert.ok(source.includes('@click="printClosureDetail"'))
assert.ok(source.includes('window.print()'))
assert.ok(!source.includes("orders/getAllOrder"))

console.log('reports ticket z tests passed')
