const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const tablesStore = fs.readFileSync(path.join(root, 'store', 'tables.js'), 'utf8')
const servicePointsStorePath = path.join(root, 'store', 'servicePoints.js')
const bornesPage = fs.readFileSync(path.join(root, 'pages', 'bornes.vue'), 'utf8')

assert.strictEqual(fs.existsSync(servicePointsStorePath), true)
assert.match(tablesStore, /\/service-points\/tables/)
assert.match(tablesStore, /\.post\('\/baseurl\/api\/v1\/service-points\/tables'/)
assert.match(tablesStore, /\.delete\(`\/baseurl\/api\/v1\/service-points\/tables\/\$\{params\}`/)

const servicePointsStore = fs.readFileSync(servicePointsStorePath, 'utf8')
assert.match(servicePointsStore, /\/service-points/)
assert.match(servicePointsStore, /system_key === 'counter'/)
assert.match(servicePointsStore, /verifyKioskPin/)
assert.match(servicePointsStore, /\/service-points\/kiosk\/verify-pin/)
assert.match(servicePointsStore, /createKiosk\(\{ dispatch \}, data\)/)
assert.match(servicePointsStore, /\.post\(\s*'\/baseurl\/api\/v1\/service-points\/kiosks',\s*data,/)
assert.match(bornesPage, /printer_ip/)
assert.match(bornesPage, /smart_print_app/)
assert.match(bornesPage, /Adresse IP de l'imprimante/)
assert.match(bornesPage, /Imprimer avec Smart Print App/)

console.log('service points store tests passed')
