const assert = require('assert')
const fs = require('fs')
const path = require('path')

const indexSource = fs.readFileSync(path.join(__dirname, '..', 'pages', 'stocks', 'index.vue'), 'utf8')
const detailSource = fs.readFileSync(path.join(__dirname, '..', 'pages', 'stocks', '_id.vue'), 'utf8')

assert.match(indexSource, /v-tabs/)
assert.match(indexSource, /Produits/)
assert.match(indexSource, /Ingredients/)
assert.match(indexSource, /Stocks bas/)
assert.match(indexSource, /Liste de courses/)
assert.match(indexSource, /Inventaire/)
assert.match(indexSource, /generateShoppingList/)
assert.match(indexSource, /setShoppingListTaken/)
assert.match(indexSource, /replenishItem/)
assert.match(indexSource, /inventoryItem/)
assert.match(indexSource, /Pris/)
assert.match(indexSource, /Reapprovisionner/)
assert.match(indexSource, /Non renseigne/)
assert.match(detailSource, /movements/)
assert.match(detailSource, /replenishment/)
assert.match(detailSource, /inventory/)

console.log('stock inventory page tests passed')
