const assert = require('assert')
const fs = require('fs')
const path = require('path')

const indexSource = fs.readFileSync(path.join(__dirname, '..', 'pages', 'stocks', 'index.vue'), 'utf8')
const detailSource = fs.readFileSync(path.join(__dirname, '..', 'pages', 'stocks', '_id.vue'), 'utf8')

assert.match(indexSource, /v-tabs/)
assert.match(indexSource, /Produits/)
assert.match(indexSource, /Ingredients/)
assert.match(indexSource, /Stocks bas/)
assert.match(indexSource, /Liste de courses/)
assert.match(indexSource, /Inventaire/)
assert.match(indexSource, /generateShoppingList/)
assert.match(indexSource, /setShoppingListTaken/)
assert.match(indexSource, /replenishItem/)
assert.match(indexSource, /inventoryItem/)
assert.match(indexSource, /Pris/)
assert.match(indexSource, /Reapprovisionner/)
assert.match(indexSource, /Non renseigne/)
assert.match(detailSource, /movements/)
assert.match(detailSource, /replenishment/)
assert.match(detailSource, /inventory/)
assert.match(detailSource, /#\[`item\.unit_price`\][\s\S]*formatEstimatedPrice\(movement\.unit_price\)/)
assert.match(detailSource, /#\[`item\.total_price`\][\s\S]*formatEstimatedPrice\(movement\.total_price\)/)
assert.match(indexSource, /const success = await this\.\$store\.dispatch\('stockInventory\/replenishItem'/)
assert.match(indexSource, /if \(success\) \{[\s\S]*this\.replenishDialog = false[\s\S]*await this\.loadStock\(\)/)
assert.match(indexSource, /filteredProducts/)
assert.match(indexSource, /filteredIngredients/)
assert.match(indexSource, /filteredShoppingList/)
assert.match(indexSource, /bulkInventory/)
assert.match(indexSource, /archiveIngredient/)
assert.match(indexSource, /deleteIngredient/)
assert.match(indexSource, /window\.print\(\)/)
assert.match(indexSource, /shoppingRowClass/)
assert.match(indexSource, /shopping-taken/)
assert.match(indexSource, /reference/)
assert.match(indexSource, /purchase_date/)
assert.match(indexSource, /const success = await this\.\$store\.dispatch\('stockInventory\/inventoryItem'/)
assert.match(indexSource, /if \(success\) \{[\s\S]*this\.inventoryDialog = false[\s\S]*await this\.loadStock\(\)/)
assert.match(detailSource, /openReplenish/)
assert.match(detailSource, /openInventory/)
assert.match(detailSource, /editItem/)
assert.match(detailSource, /archiveIngredient/)
assert.match(detailSource, /deleteIngredient/)
assert.match(detailSource, /average_unit_price/)
assert.match(detailSource, /default_supplier/)
assert.match(detailSource, /reference/)

console.log('stock inventory page tests passed')
