name: Clone, Build and Deploy Nuxt App to EC2

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone staging branch manually
        run: |
          pwd
          git clone --branch staging https://github.com/SuperJumper404/pos-app.git frontend

      - name: Install dependencies
        run: |
          pwd
          cd frontend
          npm install

      - name: Set environment variables
        run: |
          pwd
          echo 'VUE_APP_BASEURL=https://staging.smarteat.fr:5005' > frontend/.env
          echo 'ENV=staging' >> frontend/.env
          echo 'privateURL=staging.smarteat.fr' >> frontend/.env

      - name: Build Nuxt app
        run: |
          pwd
          cd frontend
          npm run generate

      - name: Upload whole frontend folder to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: 'frontend/*'
          target: '/home/ubuntu/smarteat/'

      - name: Launch frontend with pm2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            pwd
            cd /home/ubuntu/smarteat/frontend
            pwd
            pm2 delete frontend || true
            pm2 start
