name: Build and Deploy Nuxt App to EC2

on:
  push:
    branches:
      - staging

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build Nuxt app
        run: npm run generate

      - name: Upload dist folder to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: 'dist/*'
          target: '/home/ubuntu/smarteat/frontend'

      - name: Post-deploy (optional permissions or config on EC2)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "✅ Déploiement terminé dans /home/ubuntu/smarteat/frontend"
            # Par exemple : chmod -R 755 ou chown www-data selon ton serveur web
