name: Deploy to EC2

on:
  push:
    branches:
      - staging

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Cloner le projet si dossier manquant
            if [ ! -d /home/ubuntu/smarteat/frontend ]; then
              cd /home/ubuntu/smarteat
              mkdir frontend
              git clone --branch staging git@github.com:SuperJumper404/pos-app.git frontend
            fi
            cd /home/ubuntu/smarteat/frontend
            git fetch origin
            git reset --hard origin/staging
            npm install
            npx pm2 start ecosystem.config.js --env staging || npx pm2 restart frontend_smart_eat_staging
